linters:
  enable:
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - sloglint
    - spancheck
    - testifylint
    - unparam
    - unused
    - usestdlibvars
    - wsl

linters-settings:
  errorlint:
    asserts: false
  errcheck:
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
  goconst:
    ignore-tests: true
