version: "2"
linters:
  enable:
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - sloglint
    - spancheck
    - testifylint
    - unparam
    - usestdlibvars
    - wsl
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
    errorlint:
      asserts: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
