name: "Validation"
on:
  pull_request:
    types:
      - "opened"
      - "edited"
      - "reopened"
jobs:
  check-commit-message:
    name: "PR Title"
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: Check Title
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^.*(Feat|Chore|Fix):.*$'
          error: 'You need at least one of "Feat:|Chore:|Fix:" in PR title prefix.'
          excludeDescription: true
